### ISSUE TITLE
Textfield Component size props ineffective

### ISSUE THREAD

**Issue by kd4001** [cca-io/rescript-material-ui#103]
The size prop in `MaterialUi_TextField` Component is ineffective.

**Comment by jsiebern** [comment]
Sorry, I can't reproduce this. Though I had to apply a variant option for this to take effect. Without that prop it didn't seem to do anything.

The prop gets applied as it should in the JS version, so that's in MUI's hand:
```js
React.createElement(Core.TextField, {
  fullWidth: true,
  placeholder: "None",
  variant: "outlined"
})
```

<img width="1032" alt="Bildschirmfoto 2020-07-19 um 11 19 45" src="https://user-images.githubusercontent.com/6476589/87871608-cb92a080-c9b1-11ea-81a5-72d3c5bb24cf.png">

Small remark: I tested it on the `zero` branch just now. This will become the default in the next update.
